FROM node:19.5.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY build/ /app/build

# Install app dependencies
RUN npm install -g serve


# Expose port 3000 (adjust the port based on your application)
EXPOSE 3000

# CMD to run the application
CMD [ "serve", "-s build" ]